# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=poveroh
ENV POSTGRES_PASSWORD=jJVkn6vU8DvgmB0
ENV POSTGRES_DB=poveroh

# Optionally, copy SQL files or scripts to initialize the database
# These scripts will be run in alphabetical order during container initialization
#COPY ./init-scripts /docker-entrypoint-initdb.d/

# Expose the default PostgreSQL port
EXPOSE 5432